import sqlite3
from pathlib import Path
import json
import numpy as np # Added for convert_to_numpy=True
import sys # For printing progress

try:
    from sentence_transformers import SentenceTransformer
except ImportError:
    print("SentenceTransformers library not found. Please install it: pip install sentence-transformers")
    sys.exit(1)

try:
    import faiss
except ImportError:
    print("FAISS library not found. Please install it: pip install faiss-cpu (or faiss-gpu if you have CUDA)")
    sys.exit(1)


# --- Configuration ---
# Assuming medicaments.db is in the project root
DB_PATH = Path(__file__).resolve().parent.parent.parent / 'medicaments.db'
FAISS_INDEX_PATH = Path(__file__).resolve().parent / 'rcp_embeddings.faiss'
FAISS_ID_MAP_PATH = Path(__file__).resolve().parent / 'faiss_index_to_chunk_id.json'
MODEL_NAME = 'paraphrase-multilingual-mpnet-base-v2' # Or 'all-MiniLM-L6-v2' for a smaller, faster English model


# --- Main Processing Function ---
def generate_and_save_embeddings():
    """
    Fetches text chunks, generates embeddings, and saves them to a FAISS index and an ID map.
    """
    print("--- Starting Embedding Generation ---")

    # 1. Load Sentence Transformer Model
    print(f"Loading Sentence Transformer model: {MODEL_NAME}...")
    try:
        model = SentenceTransformer(MODEL_NAME)
        print("Model loaded successfully.")
    except Exception as e:
        print(f"Error loading Sentence Transformer model: {e}")
        print("This might be due to network issues if the model needs to be downloaded, or an invalid model name.")
        return # Cannot proceed without the model

    # 2. Fetch Text Chunks from Database
    conn = None
    all_chunk_texts = []
    all_chunk_ids = [] # This will store the original chunk_id from the database

    print(f"Connecting to database: {DB_PATH}")
    if not DB_PATH.exists():
        print(f"ERROR: Database file not found at {DB_PATH}. Please run previous scripts.")
        return

    try:
        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()
        print("Fetching text chunks from RCP_Chunks table...")
        # Order by chunk_id to ensure consistency if the index needs to be rebuilt
        # and for the FAISS_ID_MAP_PATH to correctly map FAISS index (row number) to chunk_id
        cursor.execute("SELECT chunk_id, chunk_text FROM RCP_Chunks ORDER BY chunk_id")
        
        for row in cursor:
            all_chunk_ids.append(row[0]) # chunk_id
            all_chunk_texts.append(row[1]) # chunk_text
            
        print(f"Fetched {len(all_chunk_texts)} text chunks.")

    except sqlite3.Error as e:
        print(f"Database error while fetching chunks: {e}")
        return
    finally:
        if conn:
            conn.close()

    if not all_chunk_texts:
        print("No text chunks found in the database. Exiting.")
        # Optionally, clean up existing index files if desired
        # FAISS_INDEX_PATH.unlink(missing_ok=True)
        # FAISS_ID_MAP_PATH.unlink(missing_ok=True)
        # print("Cleaned up any existing index files as no new data is available.")
        return

    # 3. Generate Embeddings
    print("Generating embeddings for text chunks...")
    try:
        embeddings = model.encode(all_chunk_texts, show_progress_bar=True, convert_to_numpy=True)
        print(f"Embeddings generated. Shape: {embeddings.shape}")
        if not isinstance(embeddings, np.ndarray) or embeddings.ndim != 2:
            print("ERROR: Embeddings are not a 2D numpy array. Aborting.")
            return
    except Exception as e:
        print(f"Error during embedding generation: {e}")
        return

    # 4. Build and Save FAISS Index
    if embeddings.shape[0] > 0: # Ensure there are embeddings to add
        dimension = embeddings.shape[1]
        print(f"Building FAISS index with dimension {dimension}...")
        try:
            index = faiss.IndexFlatL2(dimension)
            index.add(embeddings)
            faiss.write_index(index, str(FAISS_INDEX_PATH))
            print(f"FAISS index built and saved to {FAISS_INDEX_PATH}")
        except Exception as e:
            print(f"Error building or saving FAISS index: {e}")
            return # Do not proceed to save map if index failed

        # 5. Save FAISS ID to Chunk ID Map
        # The FAISS index generated by IndexFlatL2 uses sequential IDs from 0 to N-1.
        # These correspond directly to the order of embeddings added.
        # Since we fetched chunks ordered by chunk_id, all_chunk_ids is already our map.
        # The i-th element in all_chunk_ids is the database chunk_id for the i-th vector in FAISS.
        print(f"Saving FAISS ID to Chunk ID map (list of chunk_ids in order of FAISS index)...")
        try:
            with open(FAISS_ID_MAP_PATH, 'w', encoding='utf-8') as f:
                json.dump(all_chunk_ids, f) # Store the list of chunk_ids
            print(f"FAISS ID map saved to {FAISS_ID_MAP_PATH}")
        except IOError as e:
            print(f"Error saving FAISS ID map: {e}")
        except Exception as e:
            print(f"An unexpected error occurred while saving the ID map: {e}")
    else:
        print("No embeddings were generated (possibly due to no text chunks). Skipping FAISS index and map creation.")

    print("--- Embedding Generation Finished ---")

if __name__ == '__main__':
    generate_and_save_embeddings()
